name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build Angular
        run: npx ng build --configuration production --base-href /

      - name: Locate build output
        id: locate
        run: |
          set -e
          # Cherche dist/*/browser (SSR) puis dist/browser, puis premier dossier de dist/ contenant index.html
          CANDIDATE=$(ls -d dist/*/browser dist/browser 2>/dev/null | head -n 1 || true)
          if [ -z "$CANDIDATE" ]; then
            CANDIDATE=$(find dist -maxdepth 2 -type f -name index.html -printf '%h\n' | head -n 1 || true)
          fi
          if [ -z "$CANDIDATE" ]; then
            echo "Aucun index.html trouvé dans dist/"; exit 1
          fi
          echo "dir=$CANDIDATE" >> $GITHUB_OUTPUT
          echo "Build directory: $CANDIDATE"

      - name: Add 404.html
        run: cp '${{ steps.locate.outputs.dir }}/index.html' '${{ steps.locate.outputs.dir }}/404.html'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '${{ steps.locate.outputs.dir }}'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4